import { AspectRatioOption, StyleOption } from './types';

export const STYLE_OPTIONS: StyleOption[] = [
  {
    id: 'default',
    nameEn: 'Balanced',
    nameBn: 'স্ট্যান্ডার্ড',
    icon: '✨',
    description: 'Crisp & natural composition',
  },
  {
    id: 'photorealistic',
    nameEn: 'Photorealistic',
    nameBn: 'ফটোরিয়ালিস্টিক',
    icon: '📸',
    description: '8K, cinematic lighting & sharp lens focus',
  },
  {
    id: 'rickshaw-art',
    nameEn: 'Rickshaw Art',
    nameBn: 'রিকশা আর্ট',
    icon: '🎨',
    description: 'Traditional Bangladeshi folk art with bold vibrant colors',
  },
  {
    id: 'anime',
    nameEn: 'Anime / Manga',
    nameBn: 'অ্যানিমে',
    icon: '🌸',
    description: 'Japanese anime aesthetic with vibrant cel shading',
  },
  {
    id: 'cyberpunk',
    nameEn: 'Cyberpunk',
    nameBn: 'সাইবারপাংক',
    icon: '🌆',
    description: 'Futuristic neon lights, rain, and synthwave vibes',
  },
  {
    id: '3d-render',
    nameEn: '3D Pixar/Game',
    nameBn: 'থ্রি-ডি রেন্ডার',
    icon: '🧸',
    description: 'Octane render, Pixar-like 3D depth and soft lighting',
  },
  {
    id: 'digital-art',
    nameEn: 'Digital Art',
    nameBn: 'ডিজিটাল আর্ট',
    icon: '🖌️',
    description: 'Concept art trending on ArtStation',
  },
  {
    id: 'oil-painting',
    nameEn: 'Oil Painting',
    nameBn: 'তৈলচিত্র',
    icon: '🖼️',
    description: 'Rich canvas texture with classic brushwork',
  },
  {
    id: 'fantasy',
    nameEn: 'Epic Fantasy',
    nameBn: 'ফ্যান্টাসি',
    icon: '🔮',
    description: 'Mythical atmosphere, glowing magic, ethereal',
  },
];

export const ASPECT_RATIOS: AspectRatioOption[] = [
  { id: '1:1', label: '1:1', sublabel: 'Square (স্কয়ার)', ratio: '1:1' },
  { id: '16:9', label: '16:9', sublabel: 'Landscape (ওয়াইড)', ratio: '16:9' },
  { id: '9:16', label: '9:16', sublabel: 'Portrait (স্টোরি/রিল)', ratio: '9:16' },
  { id: '4:3', label: '4:3', sublabel: 'Classic (ক্লাসিক)', ratio: '4:3' },
  { id: '3:4', label: '3:4', sublabel: 'Vertical (ভার্টিকাল)', ratio: '3:4' },
];

export const SUGGESTED_CHAT_PROMPTS = {
  bn: [
    'বাংলাদেশের সুন্দর সুন্দর পর্যটন কেন্দ্রগুলো কী কী?',
    'একটি অনুপ্রেরণাদায়ক বাংলা কবিতা লিখে দাও',
    'কোডিং শেখার সবচেয়ে সেরা ৫টি উপায় কী?',
    'কৃত্রিম বুদ্ধিমত্তা (AI) কীভাবে কাজ করে সহজ ভাষায় বলো',
    'স্বাস্থ্যকর সকালের নাশতার একটি রুটিন দাও',
  ],
  en: [
    'Explain Quantum Computing like I am 10 years old',
    'Write a motivating modern poem about resilience',
    'Give me a clean Python code example for web scraping',
    'What are the most promising technology trends for the next 5 years?',
    'Create a 3-day travel itinerary for Kyoto, Japan',
  ],
};

export const SUGGESTED_IMAGE_PROMPTS = {
  bn: [
    'ঢাকার ঐতিহ্যবাহী রিকশা আর্ট স্টাইলে একটি গর্জনরত বাঘ',
    'বৃষ্টিভেজা রাতে নিয়ন আলোয় ঝলমলে ভবিষ্যৎ ঢাকা শহর, সাইবারপাংক স্টাইল',
    'সুন্দরবনের নদীতে একদল মায়াবী হরিণ পানি খাচ্ছে, সুর্যাস্তের আলো',
    'চাঁদের বুকে বসে ধোঁয়া ওঠা এক কাপ চা পান করছেন এক নভোচারী',
    'এক মিষ্টি পুতুলের মতো বিড়ালছানা লাল ছাতা মাথায় নিয়ে বসে আছে',
  ],
  en: [
    'A majestic royal Bengal tiger illustrated in colorful rickshaw art style',
    'Cyberpunk futuristic city in the rain with glowing neon signs and flying cars',
    'An astronaut having a hot cup of tea sitting on the moon surface, 8k',
    'Cozy wooden coffee shop interior on a rainy autumn evening, warm lighting',
    'A tiny adorable baby dragon resting inside a blooming crystal flower, 3D render',
  ],
};

export const I18N = {
  bn: {
    appTitle: 'এআই সহকারী ও ছবি জেনারেটর',
    appSubtitle: 'বুদ্ধিমান চ্যাট এবং উচ্চমানের ছবি তৈরি করুন এক ক্লিকে',
    chatMode: 'চ্যাট মোড',
    imageMode: 'ছবি জেনারেট',
    unifiedMode: 'অল-ইন-ওয়ান',
    chatPlaceholder: 'আপনার প্রশ্ন বা কথা এখানে লিখুন...',
    imagePlaceholder: 'আপনার কল্পনার ছবির বিবরণ এখানে লিখুন (যেমন: চাঁদে বসে চা খাচ্ছে একজন নভোচারী)...',
    unifiedPlaceholder: 'চ্যাট করুন অথবা লিখুন "একটি ছবি আঁকো..."',
    send: 'পাঠান',
    generating: 'জেনারেট হচ্ছে...',
    thinking: 'এআই চিন্তা করছে...',
    creatingImage: 'ছবি তৈরি করা হচ্ছে, দয়া করে অপেক্ষা করুন...',
    styleSelect: 'স্টাইল পছন্দ করুন:',
    aspectRatioSelect: 'আকার (Aspect Ratio):',
    enhancePrompt: 'প্রম্পট উন্নত করুন',
    enhancing: 'উন্নত হচ্ছে...',
    welcomeTitle: 'স্বাগতম! আমি আপনার সর্বাধুনিক এআই সহকারী 🤖',
    welcomeDesc: 'আপনি যেকোনো বিষয়ে আমার সাথে খোলামেলা কথা বলতে পারেন, কোড বুঝতে পারেন, লেখা তৈরি করতে পারেন অথবা অবিশ্বাস্য ছবি জেনারেট করতে পারেন!',
    suggestedPrompts: 'জনপ্রিয় কিছু প্রশ্ন ও আইডিয়া:',
    copyText: 'কপি করুন',
    copied: 'কপি হয়েছে!',
    readAloud: 'পড়ে শোনাও',
    downloadImage: 'ছবি ডাউনলোড',
    viewFull: 'বড় করে দেখুন',
    remixPrompt: 'এই প্রম্পট ব্যবহার করুন',
    clearChat: 'চ্যাট মুছুন',
    gallery: 'তৈরিকৃত ছবির গ্যালারি',
    noImagesYet: 'এখনও কোনো ছবি তৈরি করা হয়নি। নিচে লিখে ছবি তৈরি করুন!',
    listeningVoice: 'শুনছি... বলুন',
    voiceInput: 'ভয়েস ইনপুট',
    errorGeneral: 'দুঃখিত, কোনো সমস্যা হয়েছে। আবার চেষ্টা করুন।',
    apiKeyMissing: 'জেমিনি এপিআই কি প্রয়োজন। দয়া করে সেটিংস চেক করুন।',
    poweredBy: 'Powered by Gemini 3.8 Flash & Gemini Image AI',
  },
  en: {
    appTitle: 'AI Chatbot & Image Studio',
    appSubtitle: 'Chat with smart AI and generate stunning visuals seamlessly',
    chatMode: 'Chat Mode',
    imageMode: 'Image Creator',
    unifiedMode: 'All-in-One',
    chatPlaceholder: 'Ask anything or discuss ideas...',
    imagePlaceholder: 'Describe the image you want to create (e.g., an astronaut drinking tea on the moon)...',
    unifiedPlaceholder: 'Chat or type "Draw a picture of..."',
    send: 'Send',
    generating: 'Generating...',
    thinking: 'AI is thinking...',
    creatingImage: 'Creating your image, please wait a moment...',
    styleSelect: 'Select Visual Style:',
    aspectRatioSelect: 'Aspect Ratio:',
    enhancePrompt: 'Enhance Prompt',
    enhancing: 'Enhancing...',
    welcomeTitle: 'Welcome! I am your AI Assistant & Creative Studio 🤖',
    welcomeDesc: 'Ask me anything, brainstorm ideas, write stories or code, and generate breathtaking visuals with next-gen AI.',
    suggestedPrompts: 'Suggested inspirations to try:',
    copyText: 'Copy',
    copied: 'Copied!',
    readAloud: 'Read aloud',
    downloadImage: 'Download Image',
    viewFull: 'Enlarge',
    remixPrompt: 'Remix prompt',
    clearChat: 'Clear History',
    gallery: 'Generated Images Gallery',
    noImagesYet: 'No images generated yet. Type a prompt below to create your first masterpiece!',
    listeningVoice: 'Listening... speak now',
    voiceInput: 'Voice Input',
    errorGeneral: 'Sorry, an error occurred. Please try again.',
    apiKeyMissing: 'Gemini API key is required. Please check your configuration.',
    poweredBy: 'Powered by Gemini 3.8 Flash & Gemini Image AI',
  },
};
